export const monsterNames = [
    "Slime",
    "Goblin",
    "Skeleton",
    "Zombie",
    "Wolf",
    "Bat",
    "Orc",
    "Giant",
    "Dragon",
    "Demon",
    "Spider",
    "Ghost",
    "Vampire",
    "Werewolf",
    "Gargoyle",
    "Wraith",
    "Troll",
    "Cyclops",
    "Minotaur",
    "Harpy",
    "Mummy",
    "Elemental",
    "Chimera",
    "Behemoth",
    "Griffin",
    "Phoenix",
    "Kraken",
    "Succubus",
    "Lich",
    "Hydra",
    "Imp",
    "Serpent",
    "Centaur",
    "Yeti",
    "Manticore",
    "Specter",
    "Witch",
    "Ogre",
    "Fairy",
    "Siren",
    "Golem",
    "Basilisk",
    "Dwarf",
    "Pixie",
    "Satyr",
    "Hobgoblin",
    "Naga",
    "Cockatrice",
    "Beholder",
    "Mimic",
    "Cursed Knight",
    "Evil Wizard",
    "Dark Elf",
    "Valkyrie",
    "Thunderbird",
    "Wyvern",
    "Gryphon",
    "Shadow Beast",
    "Chaos Elemental",
    "Ancient Lizard",
    "Shapeshifter"
 ];